# ZUM - Projekt

Import potrzebnych narzędzi.

In [122]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.naive_bayes import CategoricalNB, GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, auc, roc_auc_score, average_precision_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict
from IPython.display import display, HTML

Import przygotowanej klasy Ensemble.

In [129]:
from src.ensembles import Ensemble

Plan badań
1. Modele zespołowe dla każdego z algorytmów (SVC, DecisionTreeClassifier,  CategoricalNB, GaussianNB)
2. Dla każdego z modelów zespołowych testy dla 5, 10, 50, 100 modeli w zespole.
3. Analogiczne testy dla Bagging Classifier
4. Analogiczne testy dla Random Forest Classifier (liczba drzew)
5. Testy na algorytmach konwencjonalnych
6. Wszystko wyżej dla CV = 10
7. Wszystko wyżej powtórzone dla dwóch zbiorów danych.

** dodatkowo różne opcje podzialu atrybutow na modele w modelach zespolowych

w sumie (4*4 + 4*4 + 4 + 4)*2 = 80

## Human activity

In [130]:
random_state = 3

Załadowanie danych

In [ ]:
x_train = np.loadtxt("human_activity/X_train.txt", dtype = float)
x_test = np.loadtxt("human_activity/X_test.txt", dtype = float)
y_train = np.loadtxt("human_activity/y_train.txt", dtype = int)
y_test = np.loadtxt("human_activity/y_test.txt", dtype = int)

x = np.vstack([x_train, x_test])
y = np.append(y_train, y_test)

#x_train, x_test, y_train, y_test = train_test_split(
#    x, y, test_size=0.99, random_state=random_state
#)

Funkcja pomocnicza do dyskretyzacji danych

In [110]:
def find_intervals(x_train, group_vector):  # auxilary values for data disrcetization
    intervals = np.array([np.zeros(i - 1) for i in group_vector])

    for i, features in enumerate(x_train.T):
        max_value = max(features)
        min_value = min(features)
        section_size = (max_value - min_value) / group_vector[i]
        intervals[i] = np.array(
            [min_value + section_size * j for j in range(1, group_vector[i])]
        )
    return intervals

In [111]:
intervals = find_intervals(x_train, [4] * 561)
x_train_discrete = np.array([np.digitize(column , bins=intervals[i]) for i, column in enumerate(x_train.T)]).T
x_test_discrete = np.array([np.digitize(column , bins=intervals[i]) for i, column in enumerate(x_test.T)]).T
x_discrete = np.vstack([x_train_discrete, x_test_discrete])

Funkcje do testowania klasyfikatorów

In [ ]:
def test_classifier(clf, x_train, y_train, x_test, y_test):
    clf.fit(x_train, y_train)
    
    accuracy_score = clf.score(x_test, y_test)
    y_pred_proba = clf.predict_proba(x_test)
    roc_auc = roc_auc_score(y_test, y_pred_proba, average='macro', multi_class='ovr')
    pr_auc = average_precision_score(y_test, y_pred_proba, average='macro')
    y_pred = clf.predict(x_test)
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    return accuracy_score, roc_auc, pr_auc, precision, recall, conf_matrix

In [ ]:
def test_cv_classifier(clf, x, y, n=10):
   scores = cross_val_score(clf, x, y, cv=n)
   scores_mean = scores.mean()
   return scores, scores_mean

Funkcja do wypisywania wyników

In [135]:
def print_results(accuracy_score, roc_auc, pr_auc, precision, recall, conf_matrix, scores, scores_mean):
    print("Accuracy: {:.3f}".format(accuracy_score))
    print("ROC AUC: {:.3f}".format(roc_auc))
    print("PR AUC: {:.3f}".format(pr_auc))
    print("Precision: {:.3f}".format(precision))
    print("Recall: {:.3f}".format(recall))
    print("Confusion matrix:\n", conf_matrix)
    
    print("CV scores:", end=" ")
    for score in scores:
        print("{:.3f}".format(score), end=" ")
    print()
    
    print("CV mean score: {:.3f}".format(scores_mean))

Funkcje do formatowania macierzy pomyłek i wyników z CV do lepszej prezentacji
w formie tabeli

In [ ]:
def format_conf_matrix(conf_matrix):
    formatted_matrix = '[' + ',<br> '.join(['[' + ', '.join(map(str, row)) + ']' for row in conf_matrix]) + ']'
    return formatted_matrix

# Define a function to format CV scores into multiple lines
def format_cv_scores(cv_scores):
    lines = []
    for i in range(0, len(cv_scores), 4):
        line = ', '.join(f'{score:.3f}' for score in cv_scores[i:i+3])
        lines.append(line)
    return '<br>'.join(lines)

Funkcja do testów modeli zespołowych

In [162]:
def test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier,
    model = None, 
    n_estimators_values=[5,10,50,100],
    random_state = random_state,
    min_categories = [4] * 561
    ):
    results = []
    n = n_estimators_values
    for n_estimators in n:
        if classifier == RandomForestClassifier:
            clf = classifier(n_estimators=n_estimators, random_state=random_state)
            accuracy_score, roc_auc, pr_auc, precision, recall, conf_matrix = test_classifier(clf, x_train, y_train, x_test, y_test)
            scores, scores_mean = test_cv_classifier(clf, x, y, n=10)
        elif classifier == Ensemble:
            if model == CategoricalNB:
                clf = classifier(classifier_constructor=model, classifiers_number=n_estimators, random_state=random_state, min_categories=min_categories)
            else:
                clf = classifier(classifier_constructor=model, classifiers_number=n_estimators, random_state=random_state)
            accuracy_score, roc_auc, pr_auc, precision, recall, conf_matrix = test_classifier(clf, x_train, y_train, x_test, y_test)
            scores, scores_mean = test_cv_classifier(clf, x, y, n=10)
        else:
            clf = classifier(estimator=model, n_estimators=n_estimators, random_state=random_state)
            accuracy_score, roc_auc, pr_auc, precision, recall, conf_matrix = test_classifier(clf, x_train, y_train, x_test, y_test)
            scores, scores_mean = test_cv_classifier(clf, x, y, n=10)
            
        
        results.append({
            'n': n_estimators,
            'Accuracy': round(accuracy_score, 3),
            'ROC AUC': round(roc_auc, 3),
            'PR AUC': round(pr_auc, 3),
            'Precision': round(precision, 3),
            'Recall': round(recall, 3),
            'Confusion matrix': format_conf_matrix(conf_matrix),
            'CV scores': format_cv_scores(scores),
            'CV mean score': round(scores_mean, 3)
        })

    results_df = pd.DataFrame(results)
    return results_df

### Testy na pojedynczych modelach

SVC

In [167]:
clf_svc = SVC(probability=True)
svc_accuracy_score, svc_roc_auc, svc_pr_auc, svc_precision, svc_recall,\
    svc_conf_matrix = test_classifier(clf_svc, x_train, y_train, x_test, y_test)
svc_scores, svc_scores_mean = test_cv_classifier(clf_svc, x, y, n=10)
print("SVC:")
print_results(svc_accuracy_score, svc_roc_auc, svc_pr_auc, svc_precision, svc_recall,\
    svc_conf_matrix, svc_scores, svc_scores_mean)


SVC:
Accuracy: 0.950
ROC AUC: 0.998
PR AUC: 0.990
Precision: 0.952
Recall: 0.949
Confusion matrix:
 [[488   5   3   0   0   0]
 [ 20 451   0   0   0   0]
 [ 10  26 384   0   0   0]
 [  0   2   0 438  51   0]
 [  0   0   0  29 503   0]
 [  0   0   0   0   0 537]]
CV scores: 0.971 0.931 0.879 0.947 0.970 0.974 0.961 0.956 0.953 0.968 
CV mean score: 0.951


Gaussian Naive Bayes

In [168]:
clf_gaussNB = GaussianNB()
gaussNB_accuracy_score, gaussNB_roc_auc, gaussNB_pr_auc, gaussNB_precision, gaussNB_recall,\
    gaussNB_conf_matrix = test_classifier(clf_gaussNB, x_train, y_train, x_test, y_test)
gaussNB_scores, gaussNB_scores_mean = test_cv_classifier(clf_gaussNB, x, y, n=10)
print("Gaussian Naive Bayes:")
print_results(gaussNB_accuracy_score, gaussNB_roc_auc, gaussNB_pr_auc, gaussNB_precision, gaussNB_recall,\
    gaussNB_conf_matrix, gaussNB_scores, gaussNB_scores_mean)

Gaussian Naive Bayes:
Accuracy: 0.770
ROC AUC: 0.958
PR AUC: 0.788
Precision: 0.792
Recall: 0.769
Confusion matrix:
 [[416  38  42   0   0   0]
 [  9 451  11   0   0   0]
 [ 80  83 257   0   0   0]
 [  0   7   0 368 111   5]
 [  0  15   0  54 455   8]
 [  0   3   0 211   0 323]]
CV scores: 0.765 0.686 0.577 0.754 0.683 0.704 0.786 0.792 0.815 0.698 
CV mean score: 0.726


Naive Bayes classifier for categorical features

In [169]:
clf_catNB = CategoricalNB(min_categories=[4] * 561)
catNB_accuracy_score, catNB_roc_auc, catNB_pr_auc, catNB_precision, catNB_recall,\
    catNB_conf_matrix = test_classifier(clf_catNB, x_train_discrete, y_train, x_test_discrete, y_test)
catNB_scores, catNB_scores_mean = test_cv_classifier(clf_svc, x_discrete, y, n=10)
print("Categorical Naive Bayes:")
print_results(catNB_accuracy_score, catNB_roc_auc, catNB_pr_auc, catNB_precision, catNB_recall,\
    catNB_conf_matrix, catNB_scores, catNB_scores_mean)

Categorical Naive Bayes:
Accuracy: 0.870
ROC AUC: 0.981
PR AUC: 0.898
Precision: 0.871
Recall: 0.862
Confusion matrix:
 [[452   8  36   0   0   0]
 [ 24 428  19   0   0   0]
 [ 84  63 273   0   0   0]
 [  0   2   0 377 111   1]
 [  0   1   0  33 498   0]
 [  0   0   0   0   0 537]]
CV scores: 0.954 0.917 0.859 0.951 0.964 0.970 0.937 0.937 0.950 0.966 
CV mean score: 0.940


Decision Tree Classifier

In [170]:
clf_dt = DecisionTreeClassifier()
dt_accuracy_score, dt_roc_auc, dt_pr_auc, dt_precision, dt_recall,\
    dt_conf_matrix = test_classifier(clf_dt, x_train, y_train, x_test, y_test)
dt_scores, dt_scores_mean = test_cv_classifier(clf_dt, x, y, n=10)
print("Decision Tree Classifier:")
print_results(dt_accuracy_score, dt_roc_auc, dt_pr_auc, dt_precision, dt_recall,\
    dt_conf_matrix, dt_scores, dt_scores_mean)

Decision Tree Classifier:
Accuracy: 0.855
ROC AUC: 0.911
PR AUC: 0.755
Precision: 0.853
Recall: 0.851
Confusion matrix:
 [[436  36  24   0   0   0]
 [ 67 359  45   0   0   0]
 [ 24  48 348   0   0   0]
 [  0   0   0 378 113   0]
 [  0   0   0  70 462   0]
 [  0   0   0   0   0 537]]
CV scores: 0.901 0.848 0.802 0.851 0.871 0.897 0.880 0.810 0.887 0.881 
CV mean score: 0.863


In [171]:
# Create a DataFrame to store the results
results_df = pd.DataFrame({
    'Model': ['SVC', 'Gaussian Naive Bayes', 'Categorical Naive Bayes', 'Decision Tree'],
    'Accuracy': [svc_accuracy_score, gaussNB_accuracy_score, catNB_accuracy_score, dt_accuracy_score],
    'ROC AUC': [svc_roc_auc, gaussNB_roc_auc, catNB_roc_auc, dt_roc_auc],
    'PR AUC': [svc_pr_auc, gaussNB_pr_auc, catNB_pr_auc, dt_pr_auc],
    'Precision': [svc_precision, gaussNB_precision, catNB_precision, dt_precision],
    'Recall': [svc_recall, gaussNB_recall, catNB_recall, dt_recall],
    'Confusion Matrix': [svc_conf_matrix, gaussNB_conf_matrix, catNB_conf_matrix, dt_conf_matrix],
    'CV Scores': [svc_scores, gaussNB_scores, catNB_scores, dt_scores],
    'CV Scores Mean': [svc_scores_mean, gaussNB_scores_mean, catNB_scores_mean, dt_scores_mean]
})

                     Model  Accuracy   ROC AUC    PR AUC  Precision    Recall  \
0                      SVC  0.950458  0.997831  0.990187   0.951999  0.948873   
1     Gaussian Naive Bayes  0.770275  0.957646  0.788423   0.792466  0.769066   
2  Categorical Naive Bayes  0.870377  0.980578  0.897657   0.871240  0.862318   
3            Decision Tree  0.855107  0.911203  0.754769   0.853245  0.851348   

                                    Confusion Matrix  \
0  [[488, 5, 3, 0, 0, 0], [20, 451, 0, 0, 0, 0], ...   
1  [[416, 38, 42, 0, 0, 0], [9, 451, 11, 0, 0, 0]...   
2  [[452, 8, 36, 0, 0, 0], [24, 428, 19, 0, 0, 0]...   
3  [[436, 36, 24, 0, 0, 0], [67, 359, 45, 0, 0, 0...   

                                           CV Scores  CV Scores Mean  
0  [0.970873786407767, 0.9310679611650485, 0.8786...        0.950968  
1  [0.7650485436893204, 0.6864077669902913, 0.576...        0.726087  
2  [0.954368932038835, 0.916504854368932, 0.85922...        0.940482  
3  [0.9009708737864077, 0.847

### Testy na modelach zespołowych z biblioteki scikit-learn
(n - liczba modeli w modelu zespołowym)

In [172]:
display(HTML(results_df.to_html(escape=False)))

Random Forest Classifier

In [165]:
rf_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = RandomForestClassifier,
    model = None, 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [166]:
display(HTML(rf_results.to_html(escape=False)))

Bagging Classifier

In [ ]:
bag_svc_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = BaggingClassifier,
    model = SVC(probability=True), 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [ ]:
display(HTML(bag_svc_results.to_html(escape=False)))

In [ ]:
bag_dt_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = BaggingClassifier,
    model = DecisionTreeClassifier(), 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [ ]:
display(HTML(bag_dt_results.to_html(escape=False)))

In [113]:
bag_catNB_results = test_ensemble( 
    x_discrete,
    y,
    x_train_discrete,
    y_train,
    x_test_discrete,
    y_test,
    classifier = BaggingClassifier,
    model = CategoricalNB(min_categories=[4]*561), 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [118]:
print("Bagging Categorical Naive Bayes:")
display(HTML(bag_catNB_results.to_html(escape=False)))

Bagging Categorical Naive Bayes:


In [115]:
bag_gaussNB_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = BaggingClassifier,
    model = GaussianNB(), 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [117]:
print("Bagging Gaussian Naive Bayes:")
display(HTML(bag_gaussNB_results.to_html(escape=False)))

Bagging Gaussian Naive Bayes:


### Testy na przygotowanej implementacji modeli zespołowych

Model zespołowy modeli SVC

In [132]:
ens_svc_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = Ensemble,
    model = SVC, 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [137]:
print("Ensemble SVC:")
display(HTML(ens_svc_results.to_html(escape=False)))

Ensemble SVC:


Model zespołowy modeli Gaussian Naive Bayes

In [173]:
ens_gaussNB_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = Ensemble,
    model = GaussianNB, 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [174]:
print("Ensemble Gaussian Naive Bayes:")
display(HTML(ens_gaussNB_results.to_html(escape=False)))

Ensemble Gaussian Naive Bayes:


Model zespołowy modeli Naive Bayes for categorical features

In [144]:
ens_catNB_results = test_ensemble( 
    x_discrete,
    y,
    x_train_discrete,
    y_train,
    x_test_discrete,
    y_test,
    classifier = Ensemble,
    model = CategoricalNB, 
    n_estimators_values=[5,10],
    random_state = random_state
    )

In [145]:
print("Ensemble Categorical Naive Bayes:")
display(HTML(ens_catNB_results.to_html(escape=False)))

Ensemble Categorical Naive Bayes:


Model zespołowy modeli Decision Tree Classifier

In [163]:
ens_dt_results = test_ensemble( 
    x,
    y,
    x_train,
    y_train,
    x_test,
    y_test,
    classifier = Ensemble,
    model = DecisionTreeClassifier, 
    n_estimators_values=[5,10],
    random_state = 4
    )

In [164]:
print("Ensemble Decision Tree:")
display(HTML(ens_dt_results.to_html(escape=False)))

Ensemble Decision Tree:
